apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hpe-nginx
  name: hpe-nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: eks-nginx
  template:
    metadata:
      labels:
        app: eks-nginx
    spec:
      containers:
      - image: 615650658789.dkr.ecr.ap-northeast-2.amazonaws.com/k8s-cluster-repo:v1.14
        name: hpe-nginx












